name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: make
      run: cd C/Structs\ and\ Enums/Structuring\ the\ Document/ && gcc -o main.out main.c
    - name: test
      run: ./main.out < testcase.txt > output.txt && diff output.txt expected_output.txt
